 server:
   port: 8300

 spring:
   application:
     name: app-service-member

   datasource:
     username: root
     password: root123456
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/twc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

   redis:
     host: 127.0.0.1
     port: 6379
     jedis:
       pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -1


 eureka:
   client:
     service-url:
       defaultZone: http://localhost:8100/eureka/

 ####打印MyBatias日志
 logging:
   level:
     cn.cloud.shopservicemember.mapper: DEBUG
